# Generated by Django 3.2.13 on 2022-06-12 10:58

from django.db import migrations

from .resources.products import products


def add_products(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    product_batch = [Product(**product) for product in products]
    Product.objects.bulk_create(product_batch)


def delete_products(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_products, delete_products),
    ]
